### ISSUE TITLE
Proxmox support

### ISSUE THREAD

**Issue by daviddean-x** [rouben/zfswatcher#15]
The installer won't work under Proxmox, where ZFS is native installed.

Also a question here, it's possible to connect multiple hosts to one cloud instance? 
Like Netdata, but netdata never integrated zfs pool notifications, so we're looking for another solution.

Under Proxmox we're running into this issues:

DansHomeServer# dpkg -i zfswatcher_0.4.6-1_amd64.deb
Selecting previously unselected package zfswatcher.
(Reading database ... 145795 files and directories currently installed.)
Preparing to unpack zfswatcher_0.4.6-1_amd64.deb ...
Unpacking zfswatcher (0.4.6-1) ...
dpkg: dependency problems prevent configuration of zfswatcher:
 zfswatcher depends on zfs | ubuntu-zfs | debian-zfs | zfs-dkms; however:
  Package zfs is not installed.
  Package ubuntu-zfs is not installed.
  Package debian-zfs is not installed.
  Package zfs-dkms is not installed.

dpkg: error processing package zfswatcher (--install):
 dependency problems - leaving unconfigured
Processing triggers for systemd (241-7~deb10u4) ...
Processing triggers for man-db (2.8.5-2) ...
Errors were encountered while processing:
 zfswatcher

**Comment by rouben** [comment]
Thanks for the report! [Release 0.4.7](../releases/0.4.7) should work with Proxmox.
To answer your question: no, zfswatcher is very simple "under the hood" - it just executes zpool commands and parses the output. If you're looking for a more robust Proxmox cluster monitoring solution, I would look into something more advanced, perhaps [Zabbix](https://github.com/Cosium/zabbix_zfs-on-linux)?

Speaking of Netdata, I do have it monitoring my ZFS pools, and notifications should be working, although I don't use Netdata for that; I only use it for the data visualizations. However, [monitoring](https://github.com/netdata/netdata/blob/master/health/health.d/zfs.conf) appears to be supported.
