### ISSUE TITLE
Support for SSMTP or GMAIL SMTP

### ISSUE THREAD

**Issue by vlambaard** [rouben/zfswatcher#9]
Hi, I have ssmtp setup across my systems as I do not require mail servers etc. Does zfswatcher support gmail smtp? Or can it be edited to use /usr/bin/mail?

**Comment by rouben** [comment]
I use it with GMail myself. You just have to enable SMTP/POP access to your account. It's documented here:
https://support.google.com/mail/answer/7126229?hl=en

If you use 2FA with your Google account, you can create a password just for using SMTP, called an app password:
https://support.google.com/accounts/answer/185833

Alternatively you can use something like Mailgun, who offer SMTP. Their free tier is pretty generous (up to 10,000 emails a month!), so you can use them as your SMTP gateway:
https://www.mailgun.com/pricing
